### PR TITLE
[NP-17] : connected the frontend to the backend.

### PR DESCRIPTION
**Pull request by Dhadds**

### CODE REVIEW

**Comment by Dhadds** [comment]
If you want to use main.py for testing purposes then you need to change the path for "Airports.csv" because I got upset and used an absolute path.

**Comment by tanminivan** [comment]
Is there a way to do this without moving so many files around? I feel like you're setting yourself up for spending twice as much effort to resolve merge conflicts as you did for the code change itself.

**Comment by chase-c55** [comment]
> Is there a way to do this without moving so many files around? I feel like you're setting yourself up for spending twice as much effort to resolve merge conflicts as you did for the code change itself.

Also, what is the point of the char_count directory? Is it possible to just move those files into 'backend'?

**Comment by Dhadds** [comment]
The char_count directory is the default directory that the tutorial had me create when I set up the docker containers. I think to change that we should create a ticket because it will be a little bit of work tinkering with everything and movig the files. I'm thinking we can make a new ticket to refactor the code so the directories are more organized. Also a ticket to make error handling for the front end.

**Comment by tanminivan** [comment]
Sorry, but this is a hard no from me. This sounds like code in progress that is not complete. Moving directories around because the tutorial said so only to move it back again is setting yourself up to do 10x the work of resolving conflicts instead of doing it the right way the first time.

**Comment by Dhadds** [comment]
If delete char_count directory and hello_world and move all of the code around so that the directories look good then there will probably be merge conflicts anyway. If that's the route we want to go it will probably take me another week or so to troubleshoot and move everything so I'll close the merge request and submit another one later.

**Pull request closed without merging**
